<a href="https://colab.research.google.com/github/hemidovaqil/turboaz-cars-analysis/blob/main/Turboaz_cars_analysis2.2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Statistical Analysis (t-test and confidence interval)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

sns.set(style="whitegrid")

In [ ]:
df = pd.read_csv("cars.csv")
df.head()

,id_x,car_rel_url_x,datetime_scrape,name,price_x,currency_x,datetime_product,city,day,hour,...,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Yürüş,Ötürücü,Şəhər,car_details_id_y,car_rel_url,extra_info
0,3c234145-d57a-4ad6-9448-d43810fc3392,/autos/8748840-hyundai-i30,2024-09-13 20:32:19.751157+00,Hyundai i30,15000.0,AZN,"Bakı, dünən 23:28",bakı,13.09.2024,23:28,...,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,270 000 km,Ön,Bakı,8d84d800-fafd-4d5c-b640-f47bd6c5ac20,/autos/8748840-hyundai-i30,Yüngül lehimli disklər* ABS* Mərkəzi qapanma* ...
1,c74ea36f-6be1-4de4-926d-e117197dcf00,/autos/8475807-lada-vaz-niva-travel,2024-09-13 20:32:19.751157+00,LADA (VAZ) Niva Travel,23700.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,...,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5,0 km,Tam,Bakı,2cf8b84b-adaf-467a-8f06-3dabcf866c8a,/autos/8475807-lada-vaz-niva-travel,Yüngül lehimli disklər* ABS* Kondisioner* Otur...
2,9cefceb0-024d-4581-a869-a3c2c68a9f95,/autos/8739686-toyota-land-cruiser,2024-09-13 20:32:19.751157+00,Toyota Land Cruiser,35600.0,$,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,...,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8+,164 750 km,Tam,Bakı,22bb3704-ebe7-4357-ba2f-1806d1a7042b,/autos/8739686-toyota-land-cruiser,Yüngül lehimli disklər* ABS* Lyuk* Mərkəzi qap...
3,459cc337-fb63-48de-9694-41554923d311,/autos/8712597-hyundai-elantra,2024-09-13 20:32:19.751157+00,Hyundai Elantra,26700.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,...,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,NaN,126 000 km,Ön,Bakı,e0d16dac-4091-4417-916e-cadeff600f95,/autos/8712597-hyundai-elantra,Yüngül lehimli disklər* ABS* Lyuk* Yağış senso...
4,6c5ee8d8-1c6f-4fad-a694-957a4c43c25d,/autos/8674773-toyota-prius,2024-09-13 20:32:19.751157+00,Toyota Prius,10500.0,AZN,"Bakı, dünən 23:59",bakı,13.09.2024,23:59,...,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,354 000 km,Ön,Bakı,82078856-0d07-4a0d-8123-69c2e5002e07,/autos/8674773-toyota-prius,Arxa görüntü kamerası

In [ ]:
df.info()
df.describe()

# Проверка пропусков
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12075 entries, 0 to 12074
Data columns (total 56 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_x                      12075 non-null  object
 1   car_rel_url_x             12075 non-null  object
 2   datetime_scrape           12075 non-null  object
 3   name                      12075 non-null  object
 4   price_x                   12075 non-null  float64
 5   currency_x                12075 non-null  object
 6   datetime_product          12075 non-null  object
 7   city                      12075 non-null  object
 8   day                       12075 non-null  object
 9   hour                      12075 non-null  object
 10  attributes                12075 non-null  object
 11  production_year           12075 non-null  int64
 12  engine_displacement_num   12075 non-null  float64
 13  engine_displacement_unit  12075 non-null  object
 14  kilometrage_num           12075 non-null  int64
 15  kilometrage_unit          12075 non-null  object
 16  barter                    4157 non-null   object
 17  loan                      2901 non-null   object
 18  salon                     3534 non-null   object
 19  spare_parts               36 non-null     object
 20  vip                       5576 non-null   object
 21  featured                  2996 non-null   object
 22  img_url                   12075 non-null  object
 23  id_y                      12075 non-null  object
 24  cars_id                   12075 non-null  object
 25  car_rel_url_y             12075 non-null  object
 26  datetime                  12075 non-null  object
 27  description               11779 non-null  object
 28  price_y                   12075 non-null  float64
 29  currency_y                12075 non-null  object
 30  owner_name                8444 non-null   object
 31  shop_name                 3627 non-null   object
 32  phone                     12071 non-null  float64
 33  updated                   12075 non-null  object
 34  views                     12075 non-null  int64
 35  vin                       897 non-null    object
 36  car_details_id_x          12075 non-null  object
 37  Ban növü                  12075 non-null  object
 38  Buraxılış ili             12075 non-null  int64
 39  Hansı bazar üçün yığılıb  8684 non-null   object
 40  Marka                     12075 non-null  object
 41  Model                     12075 non-null  object
 42  Mühərrik                  12075 non-null  object
 43  Qəzalı                    36 non-null     object
 44  Rəng                      12075 non-null  object
 45  Sahiblər                  7976 non-null   object
 46  Sürətlər qutusu           12075 non-null  object
 47  Vəziyyəti                 12075 non-null  object
 48  Yeni                      12075 non-null  object
 49  Yerlərin sayı             9165 non-null   object
 50  Yürüş                     12075 non-null  object
 51  Ötürücü                   12075 non-null  object
 52  Şəhər                     12075 non-null  object
 53  car_details_id_y          12075 non-null  object
 54  car_rel_url               12074 non-null  object
 55  extra_info                12074 non-null  object
dtypes: float64(4), int64(4), object(48)
memory usage: 5.2+ MB

id_x                            0
car_rel_url_x                   0
datetime_scrape                 0
name                            0
price_x                         0
currency_x                      0
datetime_product                0
city                            0
day                             0
hour                            0
attributes                      0
production_year                 0
engine_displacement_num         0
engine_displacement_unit        0
kilometrage_num                 0
kilometrage_unit                0
barter                       7918
loan                         9174
salon                        8541
spare_parts                 12039
vip                          6499
featured                     9079
img_url                         0
id_y                            0
cars_id                         0
car_rel_url_y                   0
datetime                        0
description                   296
price_y                         0
currency_y                      0
owner_name                   3631
shop_name                    8448
phone                           4
updated                         0
views                           0
vin                         11178
car_details_id_x                0
Ban növü                        0
Buraxılış ili                   0
Hansı bazar üçün yığılıb     3391
Marka                           0
Model                           0
Mühərrik                        0
Qəzalı                      12039
Rəng                            0
Sahiblər                     4099
Sürətlər qutusu                 0
Vəziyyəti                       0
Yeni                            0
Yerlərin sayı                2910
Yürüş                           0
Ötürücü                         0
Şəhər                           0
car_details_id_y                0
car_rel_url                     1
extra_info                      1
dtype: int64

In [ ]:
print(df.columns)

Index(['id_x', 'car_rel_url_x', 'datetime_scrape', 'name', 'price_x',
       'currency_x', 'datetime_product', 'city', 'day', 'hour', 'attributes',
       'production_year', 'engine_displacement_num',
       'engine_displacement_unit', 'kilometrage_num', 'kilometrage_unit',
       'barter', 'loan', 'salon', 'spare_parts', 'vip', 'featured', 'img_url',
       'id_y', 'cars_id', 'car_rel_url_y', 'datetime', 'description',
       'price_y', 'currency_y', 'owner_name', 'shop_name', 'phone', 'updated',
       'views', 'vin', 'car_details_id_x', 'Ban növü', 'Buraxılış ili',
       'Hansı bazar üçün yığılıb', 'Marka', 'Model', 'Mühərrik', 'Qəzalı',
       'Rəng', 'Sahiblər', 'Sürətlər qutusu', 'Vəziyyəti', 'Yeni',
       'Yerlərin sayı', 'Yürüş', 'Ötürücü', 'Şəhər', 'car_details_id_y',
       'car_rel_url', 'extra_info'],
      dtype='object')

The test results show a statistically significant difference between the groups (p-value < 0.05).
The confidence interval does not include zero, confirming the presence of an effect.